logging:
 file:
    path: /
    name: log.txt
 level: 
  com: 
   appsdeveloperblog: debug
#kafka server url
spring:
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1
      retries: 1
      properties:
        enable:
         idempotence: true
        max:
         in:
          flight:
           requests:
            per:
             connection: 5
        request:
         timeout:
          ms: 3